### ISSUE TITLE
Switch over to the Angular app

### ISSUE THREAD

**Issue by dfederm** [dfederm/ClickerHeroesTracker#109]
This is tracking all the features needed for feature parity.

Pages:
- [x] Home page
- [x] Log in
  - [x] With password
  - [x] External logins #137
- [x] Register #131 
  - [x] With password
  - [x] With external provider
- [x] Password reset
- [x] Feedback #132 
- [x] News
- [x] Manage page
  - [x] Settings #133
  - [x] Change password
  - [x] Add password
  - [x] External providers
- [x] Clans
- [x] Upload
- [x] Calculator
- [x] Dashboard
- [x] Uploads list
- [x] Progress #134
- [x] Compare progress #135 

Other stuff:
- [x] Auth token refresh
- [x] Send user information down to client #140
- [x] User settings sync #136
- [x] Bundling via Webpack
- [x] Ad refresh on route change
- [x] Include App insights module ([reference](https://github.com/Microsoft/ApplicationInsights-js#import-as-a-module-and-initialize-dynamically-download-full-application-insights-script-from-cdn))
- [x] App insights events, eg pageView on route change and setting the authenticated user #139
- [x] Reload on version change #138
- [x] Loading spinner during async calls
- [x] Upload page buttons: View data, Delete (need confirm), and share
- [x] Admin commands
- [x] Don't show UI until auth is attempted
- [x] Microsoft login no longer seems to work
